Task 9.2. finished.
MSajkiewicz/Marcin-Sajkiewicz-Kodilla-Java pull request #17
Opened 2019-10-06 08:45 UTC by MSajkiewicz

Zadanie: stworzenie serwisu zamówień produktów

2019-10-06 16:12 UTC, MARudnicki requested changes
W module brakuje pliku build.gradle. Rowniez w settings.gradle brakuje wpisu o nowym module

2019-10-06 16:15 UTC, MARudnicki requested changes
Klasy powinny byc podzielony wg. funkcjonalnosci na pakiety
np
com.kodilla.good.patterns.challenges.orders
com.kodilla.good.patterns.challenges.models 
itd
tak aby klasa z main pozostala jako jedyna bezposrednio w 
com.kodilla.good.patterns.challenges

2019-10-06 16:15 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/CarOrderRepository.java
> +    }
Dobrze jakby metody createOrder, order itd coś jednak robily. Conajmniej printowaly operacje ktora wykonuja

2019-10-07 15:19 UTC, MSajkiewicz commented
Zrobiłem update. Nie przygotowałem jeszcze pliku build.gradle  - nie wiem jak to prawidłowo zrobić.

2019-10-08 06:39 UTC, closed without merging