Task 9.4. finished.
MSajkiewicz/Marcin-Sajkiewicz-Kodilla-Java pull request #18
Opened 2019-10-06 14:33 UTC by MSajkiewicz

Zadanie: Wyzwanie - Food2Door

2019-10-06 16:17 UTC, MARudnicki requested changes
brakuje wpisu o nowym module w settings.gradle w roocie. 
Dodatkowo settings.gradle w tym module jest do wyrzucenia (powinien byc tylko jeden w roocie)

2019-10-06 16:18 UTC, MARudnicki requested changes

2019-10-06 16:18 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/Food2Door/OrderProcessor.java
> +        order.getSupplier().process(order);
to jest b. ubogie rozwiazanie. Dobrze byloby dac tutaj jakas minimalna mechanike

2019-10-08 11:52 UTC, MSajkiewicz commented
Update.

2019-10-09 06:20 UTC, merged